# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Путь к картинке'),
        ),
    ]
